# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://blog.solonovamax.gay/"


# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true
paginate = 10
summaryLength = 0

[outputs]
home = ["HTML", "RSS", "JSON"]

[imaging]
anchor = "Center"
bgColor = "#ffffff"
hint = "photo"
quality = 100
resampleFilter = "Box"
[imaging.exif]
disableDate = false
disableLatLong = true
excludeFields = ".*"
includeFields = ""


[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true
[minify.tdewolff]
[minify.tdewolff.css]
keepCSS2 = true
precision = 0
[minify.tdewolff.html]
keepComments = false
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepWhitespace = false
[minify.tdewolff.js]
keepVarNames = false
noNullishOperator = false
precision = 0
[minify.tdewolff.json]
keepNumbers = false
precision = 0
[minify.tdewolff.svg]
keepComments = false
precision = 0
[minify.tdewolff.xml]
keepWhitespace = false
